linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goimports
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  lll:
    line-length: 140
    tab-width: 4
  staticcheck:
    checks: [ "all", -SA5001 ]

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - lll
        - goerr113
