version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-eleicoes:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db.local

  golang:
    image: golang:1.19-alpine
    volumes:
      - .:/go/elections
    working_dir: /go/elections

volumes:
  db-eleicoes:
    driver: local
