BEGIN;

CREATE TABLE relatorio_urna
(
    dt_geracao VARCHAR(10) NOT NULL,
    hh_geracao TIME NOT NULL,
    ano_eleicao INT NOT NULL,
    cd_tipo_eleicao INT NOT NULL,
    nm_tipo_eleicao VARCHAR NOT NULL,
    cd_pleito INT NOT NULL,
    dt_pleito VARCHAR(10) NOT NULL,
    nr_turno INT NOT NULL,
    cd_eleicao INT NOT NULL,
    ds_eleicao VARCHAR(50) NOT NULL,
    sg_uf VARCHAR(2) NOT NULL,
    cd_municipio INT NOT NULL,
    nm_municipio VARCHAR(100) NOT NULL,
    nr_zona INT NOT NULL,
    nr_secao INT NOT NULL,
    nr_local_votacao INT NOT NULL,
    cd_cargo_pergunta INT NOT NULL,
    ds_cargo_pergunta VARCHAR(20) NOT NULL,
    nr_partido INT NOT NULL,
    sg_partido VARCHAR NOT NULL,
    nm_partido VARCHAR NOT NULL,
    dt_bu_recebido VARCHAR(19) NOT NULL,
    qt_aptos INT NOT NULL,
    qt_comparecimento INT NOT NULL,
    qt_abstencoes INT NOT NULL,
    cd_tipo_urna INT NOT NULL,
    ds_tipo_urna VARCHAR(20) NOT NULL,
    cd_tipo_votavel INT NOT NULL,
    ds_tipo_votavel VARCHAR(20) NOT NULL,
    nr_votavel INT NOT NULL,
    nm_votavel VARCHAR(20) NOT NULL,
    qt_votos INT NOT NULL,
    nr_urna_efetivada INT NOT NULL,
    cd_carga_1_urna_efetivada VARCHAR(30) NOT NULL,
    cd_carga_2_urna_efetivada VARCHAR(10) NOT NULL,
    cd_flashcard_urna_efetivada VARCHAR(20) NOT NULL,
    dt_carga_urna_efetivada VARCHAR(19) NOT NULL,
    ds_cargo_pergunta_secao VARCHAR(10) NOT NULL,
    ds_agregadas VARCHAR NOT NULL,
    dt_abertura VARCHAR(19) NOT NULL,
    dt_encerramento VARCHAR(19) NOT NULL,
    qt_eleitores_biometria_nh INT NOT NULL,
    dt_emissao_bu VARCHAR(19) NOT NULL,
    nr_junta_apuradora INT NOT NULL,
    nr_turma_apuradora INT NOT NULL,
    PRIMARY KEY (nr_urna_efetivada, nr_votavel)
);

COMMIT;
